FEATURES = {
    'Operating Gross Margin': 0,
    'Tax rate (A)': 1,
    'Net Value Per Share (A)': 2,
    'Persistent EPS in the Last Four Seasons': 3,
    'Cash Flow Per Share': 4,
    'Revenue Per Share (Yuan ¥)': 5,
    'After-tax Net Profit Growth Rate': 6,
    'Quick Ratio': 7,
    'Total debt/Total net worth': 8,
    'Debt ratio %': 9,
    'Contingent liabilities/Net worth': 10,
    'Inventory and accounts receivable/Net value': 11,
    'Total Asset Turnover': 12,
    'Operating profit per person': 13,
    'Allocation rate per person': 14,
    'Working Capital to Total Assets': 15,
    'Quick Assets/Total Assets': 16,
    'Current Assets/Total Assets': 17,
    'Cash/Total Assets': 18,
    'Cash/Current Liability': 19,
    'Operating Funds to Liability': 20,
    'Working Capital/Equity': 21,
    'Long-term Liability to Current Assets': 22,
    'Total expense/Assets': 23,
    'Fixed Assets to Assets': 24,
    'Equity to Long-term Liability': 25,
    'Cash Flow to Total Assets': 26,
    'Cash Flow to Liability': 27,
    'CFO to Assets': 28,
    'Cash Flow to Equity': 29,
    'Current Liability to Current Assets': 30,
    'Liability-Assets Flag': 31,
    'Net Income to Total Assets': 32,
    "Net Income to Stockholder's Equity": 33,
    'Equity to Liability': 34
} 